### PR TITLE
handle empty data sets in max() (SOFTWARE-3117)

### PR DESCRIPTION
**Pull request by edquist**

### CODE REVIEW

**Comment by edquist** [comment]
@djw8605, does it seem reasonable to pretend `max` is `1` here when the data set is empty?

**Comment by djw8605** [comment]
Would it be bad if the max was 0?

**Comment by edquist** [comment]
No I think it's probably fine either way.  As far as i can tell, the max value is only used for setting the y-range:
```
+        max_ax = max(data or [1])*1.1
         if max_ax <= 10:
             self.ax.set_ylim(-0.1, max_ax)
         else:
             self.ax.set_ylim(-0.5, max_ax)
```

So the question is, what do we want the y-range to be for an empty data set?  (-0.1, 0), (-0.1, 1.1), or something else?  (eg, (-0.1, 0.1) ?)

**Comment by edquist** [comment]
Updated to set `max_ax = 0` if the `data` list is empty.

**Pull request merged**
